import { NextUIProvider } from "@nextui-org/react"
import "./globals.css";
import Header from "@/components/UI/Header";

export const metadata = {
  title: 'Rick & Morty One',
  description: 'Generated by Next.js, project Rick and Morty One, a better version than previos project Rick and Morty.',
  keywords: 'Rick and Morty, API, Next, Project, Science Fiction, Animated Series',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className="h-screen">
        <NextUIProvider>
          <Header />
          <main className="container mx-auto ">
            <h1 className="mx-auto">Rick and Morty ONE</h1>
            {children}
          </main>
        </NextUIProvider>
      </body>
    </html>
  )
}
