import "./globals.css";
import Header from "@/components/UI/Header/Header";
import { Providers } from "./providers"; // Importa los providers correctamente

export const metadata = {
  title: 'Rick & Morty One',
  description: 'Generated by Next.js, project Rick and Morty One, a better version than previous project Rick and Morty.',
  keywords: 'Rick and Morty, API, Next, Project, Science Fiction, Animated Series',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-screen">
        <Providers> {/* Ya incluye el ErrorBoundary */}
          <Header />
          <main className="container mx-auto">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
