import { NextUIProvider } from "@nextui-org/react"

export const metadata = {
  title: 'Rick & Morty One',
  description: 'Generated by Next.js, project Rick and Morty One, a better version than previos project Rick and Morty.',
  keywords: 'Rick and Morty, API, Next, Project, Science Fiction, Animated Series',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <NextUIProvider>
          <h1>Rick and Morty ONE</h1>
          {children}
        </NextUIProvider>
      </body>
    </html>
  )
}
